<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-C5JQGMV1" failures="2" tests="17" name="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" time="63.252" errors="0" timestamp="07 Jan 2019 20:09:27 GMT" skipped="10">
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="browserproperty" time="1.202"/>
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="navigateURL" time="7.137"/>
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="getPageInfo" time="0.028">
    <skipped/>
  </testcase> <!-- getPageInfo -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="getPageInfo" time="0.032">
    <failure message="expected [ Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [ Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer.getPageInfo(AmazonSearch_RetryAnalyzer_AnnotationTransformer.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getPageInfo -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="getPageInfo" time="0.029">
    <skipped/>
  </testcase> <!-- getPageInfo -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="getPageInfo" time="0.805">
    <skipped/>
  </testcase> <!-- getPageInfo -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="getPageInfo" time="0.114">
    <skipped/>
  </testcase> <!-- getPageInfo -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="getPageInfo" time="0.049">
    <skipped/>
  </testcase> <!-- getPageInfo -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="amazonsearch" time="14.332"/>
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="amazonsearch" time="10.548"/>
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="amazonsearch" time="10.472"/>
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="results" time="3.090">
    <skipped/>
  </testcase> <!-- results -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="results" time="3.085">
    <skipped/>
  </testcase> <!-- results -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="results" time="3.079">
    <skipped/>
  </testcase> <!-- results -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="results" time="3.103">
    <skipped/>
  </testcase> <!-- results -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="results" time="3.062">
    <skipped/>
  </testcase> <!-- results -->
  <testcase classname="com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer" name="results" time="3.085">
    <failure message="expected [100] but found [24]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [100] but found [24]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer.results(AmazonSearch_RetryAnalyzer_AnnotationTransformer.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- results -->
</testsuite> <!-- com.testng1.AmazonSearch_RetryAnalyzer_AnnotationTransformer -->
